name: Delete old Workflows

on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{github.repository}}
          older-than-seconds: 86400
          what-if: false
          # older-than-seconds: 3600
          # created-before: "2021-12-08T16:34:00Z"
          # actor: test@test.com
          # branch: main
          # event: push
          # event: completed
          # maximum-workflow-runs-to-keep: 0
          # what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
